
name: Playwright Tests

#quyền để wfl chạy đúng
permissions:
  contents: write
  pages: write
  id-token: write


#check nhánh để chạy
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]


concurrency:
  group: playwright-e2e
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 250
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: BigTime Pre Version 1.0.14
      AUTHOR: hoanghai
      PLATFORM: Ubuntu
      BROWSER: Chromium, Edge, Firefox

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      # Cache dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
            

      # Install dependencies
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx playwright test
      
      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Generate Allure environment
      - name: Generate Allure environment
        run: npx ts-node scripts/generate-env.ts

      # Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EMPLOYEE_USERNAME: ${{ secrets.EMPLOYEE_USERNAME }}
          EMPLOYEE_PASSWORD: ${{ secrets.EMPLOYEE_PASSWORD }}
          EMPLOYEE2_USERNAME: ${{ secrets.EMPLOYEE2_USERNAME }}
          EMPLOYEE2_PASSWORD: ${{ secrets.EMPLOYEE2_PASSWORD }}
          MANAGER_TEAM_USERNAME: ${{ secrets.MANAGER_TEAM_USERNAME }}
          MANAGER_TEAM_PASSWORD: ${{ secrets.MANAGER_TEAM_PASSWORD }}